function props = getLfpProperties(obj)
    % Returns the output of a text box describing the LFP
    props = sprintf([
                     'LFP Experiment object populated with:\n', ...
                     '  Number of Tetrodes: %d\n', ...
                     '  Length of LFP: %d Samples\n', ...
                     '  Time Vector with: %d time points\n', ...
                     '  Sampling Frequency: %.2f Hz\n', ...
                     '  Total Time: %.3f seconds\n', ...
                     '  Time Step: %.2f ms\n', ...
                     ], ...
                     obj.num_tetrodes, ...
                     obj.num_samples, ...
                     length(obj.time_vec), ...
                     obj.sf, ...
                     obj.total_time, ...
                     (obj.time_vec(2) - obj.time_vec(1)) * 1000.0);
end